import type { Permission, Role, RoleCode } from "@/types";

const ALL: Permission[] = [
  "dashboard.view",
  "orders.view",
  "orders.manage",
  "orders.assigned.view",
  "products.view",
  "products.manage",
  "stock.view",
  "stock.manage",
  "pos.use",
  "logistics.view",
  "logistics.manage",
  "customers.view",
  "customers.manage",
  "suppliers.view",
  "suppliers.manage",
  "finance.view",
  "finance.manage",
  "reports.view",
  "users.view",
  "users.manage",
  "settings.view",
  "settings.manage",
  "driver.space",
];

export const ROLES: Record<RoleCode, Role> = {
  ADMIN: {
    code: "ADMIN",
    label: "Administrateur",
    description: "Accès total à toutes les sections et à la configuration.",
    permissions: ALL.filter((p) => p !== "driver.space" && p !== "orders.assigned.view"),
    enabled: true,
  },
  GERANT: {
    code: "GERANT",
    label: "Gérant",
    description: "Gestion opérationnelle : commandes, stock, POS, clients, logistique.",
    permissions: [
      "dashboard.view",
      "orders.view",
      "orders.manage",
      "products.view",
      "products.manage",
      "stock.view",
      "stock.manage",
      "pos.use",
      "logistics.view",
      "logistics.manage",
      "customers.view",
      "customers.manage",
      "suppliers.view",
      "suppliers.manage",
      "finance.view",
      "reports.view",
      "users.view",
      "settings.view",
      "settings.manage",
    ],
    enabled: true,
  },
  LIVREUR: {
    code: "LIVREUR",
    label: "Livreur",
    description: "Commandes assignées, livraison, scan et vente au poste si autorisé.",
    permissions: ["orders.assigned.view", "driver.space", "pos.use"],
    enabled: true,
  },
  CAISSIER: {
    code: "CAISSIER",
    label: "Caissier",
    description: "Ventes au comptoir et clôture de caisse.",
    permissions: ["pos.use", "customers.view", "dashboard.view"],
    enabled: true,
  },
  MAGASINIER: {
    code: "MAGASINIER",
    label: "Magasinier",
    description: "Stock, entrées/sorties et inventaires.",
    permissions: ["stock.view", "stock.manage", "products.view", "dashboard.view"],
    enabled: true,
  },
  COMPTABLE: {
    code: "COMPTABLE",
    label: "Comptable",
    description: "Finance, dépenses, rapports.",
    permissions: ["finance.view", "finance.manage", "reports.view", "dashboard.view"],
    enabled: true,
  },
  RESP_LOGISTIQUE: {
    code: "RESP_LOGISTIQUE",
    label: "Responsable logistique",
    description: "Suivi et assignation des livraisons.",
    permissions: ["logistics.view", "logistics.manage", "orders.view", "dashboard.view"],
    enabled: true,
  },
};

export const ROLE_LIST = Object.values(ROLES);
